### PR TITLE
Add Option to Skip Sections During Extract

### PR DESCRIPTION
**Pull request by patbakdev**
I prefer to have a single output file with all transactions (entities) sorted by date instead of the default behavior to add a section for each imported file. This option will accomplish that.

### CODE REVIEW

**Comment by dnicolodi** [comment]
Sections are there to allow to easily make sense of the output, especially in presence of duplicates (the order in which the input files are processed matters). If you don't like the section, just post-process the output to remove them:
```python
import click
from beancount.parser import parser
from beancount.parser import printer

@click.command()
@click.argument('ledger')
def main(ledger):
    entries, errors, options = parser.parse_file(ledger)
    printer.print_entries(entries)

if __name__ == '__main__':
    main()
```

**Comment by patbakdev** [comment]
Thanks. I didn't think re-parse it. I'll give that a go.

**Comment by dnicolodi** [comment]
I much prefer composability to adding many options to tools. Since a long while we have an idea for a `bean-gadget` tool that implements this sort of simple command line tools, but no one has found the time to put it together yet.

**Comment by patbakdev** [comment]
Makes sense. I am basically building my own personal version of "bean-gadget" for my purposes with commands to download, commit/backup, import (calls out to beangulp), and export (custom exporters for tax filing, reporting, etc.) As part of that I had hacked together a bench of changes to beangulp as I went along. Had a few hours available so I thought I would clean it up and see if it was of value to the wider groups. 😄

**Pull request closed without merging**
